<?php

namespace App\Models;

use App\Casts\UnixTimestamp;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class CharacterTimers extends Model
{
    /**
     * Lazy strength regeneration.
     *
     * Strength used to be regenerated by a pg_cron job ("strength-recovery")
     * running `strength = LEAST(100.00, strength + 8.333)` every 5 minutes over
     * every live character, row-locking character_timers rows that players
     * also lock in their own transactions (lock convoys / deadlocks / p99
     * spikes). The stored `strength` is now the value at `strength_updated_at`
     * and the effective value is derived on read (see strength()).
     *
     * The column is decimal(5,2), so each cron tick stored
     * round(s + 8.333, 2) == s + 8.33 for any 2-dp s. We replay that exactly
     * in integer hundredths: +833 per elapsed 300s tick, capped at 100.00.
     */
    public const STRENGTH_MAX_CENTS      = 10000;   // 100.00
    public const STRENGTH_TICK_SECONDS   = 300;     // cron ran every 5 minutes
    public const STRENGTH_PER_TICK_CENTS = 833;     // round(+8.333, 2) at decimal(5,2)

    protected $table = 'character_timers';

    public $timestamps = false;

    protected $fillable = [
        'character_id',
        'next_work_at',
        'next_action_at',
        'next_travel_at',
        'next_talents_at',
        'next_study_at',
        'next_conflict_at',
        'hospital_until',
        'protection_until',
        'hospital_reason',
        'jail_until',
        'strength',
        'last_relocation_at',
        'pending_relocation_city_id',
        'last_actioned_at',
    ];

    protected $casts = [
        'next_work_at' => UnixTimestamp::class,
        'next_action_at' => UnixTimestamp::class,
        'next_travel_at' => UnixTimestamp::class,
        'next_talents_at' => UnixTimestamp::class,
        'next_study_at' => UnixTimestamp::class,
        'next_conflict_at' => UnixTimestamp::class,
        'hospital_until' => UnixTimestamp::class,
        'protection_until' => UnixTimestamp::class,
        'jail_until' => UnixTimestamp::class,
        // 'strength' has no cast: the strength() Attribute below formats it
        // exactly like the former 'decimal:2' cast (2-dp string).
        'strength_updated_at' => UnixTimestamp::class,
        'last_actioned_at' => UnixTimestamp::class,
    ];

    /**
     * Reading `strength` returns the effective (regenerated) value; writing it
     * also stamps `strength_updated_at`, so every Eloquent write path
     * (update(), create(), fill, property assignment) stays consistent.
     * Query-builder writes (DB::table('character_timers')->update([...]))
     * bypass this and MUST set strength_updated_at themselves.
     */
    protected function strength(): Attribute
    {
        return Attribute::make(
            get: fn ($value, array $attributes) => $value === null
                ? null
                : self::effectiveStrength($value, $attributes['strength_updated_at'] ?? null),
            set: fn ($value) => [
                'strength'            => $value,
                'strength_updated_at' => now()->getTimestamp(),
            ],
        );
    }

    /**
     * Pure function: effective strength (2-dp string, same shape as the old
     * 'decimal:2' cast) for a stored value last written at $updatedAt (unix
     * seconds). Equivalent to applying LEAST(100.00, s + 8.333) on a
     * decimal(5,2) column once per 5-minute clock boundary crossed since then.
     */
    public static function effectiveStrength(int|float|string $stored, int|string|null $updatedAt, ?int $now = null): string
    {
        $cents = (int) round(((float) $stored) * 100);

        // Missing timestamp (partial select) => no regen info; return as stored.
        // Already >= 100 => the cron never touched it (WHERE strength < 100).
        if ($updatedAt !== null && $cents < self::STRENGTH_MAX_CENTS) {
            $now   ??= now()->getTimestamp();
            // Count the 5-minute clock boundaries crossed since the write, exactly
            // like the cron (which ran at :00, :05, ... UTC), so the first tick after
            // a reset still lands 0-300s later and refill time is unchanged.
            $ticks   = max(0, intdiv($now, self::STRENGTH_TICK_SECONDS) - intdiv((int) $updatedAt, self::STRENGTH_TICK_SECONDS));
            if ($ticks > 0) {
                $cents = (int) min(self::STRENGTH_MAX_CENTS, $cents + $ticks * self::STRENGTH_PER_TICK_CENTS);
            }
        }

        return number_format($cents / 100, 2, '.', '');
    }

    //! hospital_until bigint DEFAULT '0'::bigint NOT NULL,
    public function character(): BelongsTo
    {
        return $this->belongsTo(Character::class);
    }
}
